// Generated by CoffeeScript 1.7.1
var Stopwatch, should;

should = require('chai').should();

Stopwatch = require('../lib/utils.js').Stopwatch;

describe('Construction', function() {
  it('with deactivated autostart', function() {
    var sw;
    sw = new Stopwatch(false);
    (sw.startedAt == null).should.be["true"];
    (sw.stoppedAt == null).should.be["true"];
    sw = Stopwatch.create(false);
    (sw.startedAt == null).should.be["true"];
    return (sw.stoppedAt == null).should.be["true"];
  });
  return it('with activated autostart', function() {
    var sw;
    sw = new Stopwatch;
    sw.startedAt.should.be.above(1412706791719);
    (sw.stoppedAt == null).should.be["true"];
    sw = Stopwatch.create();
    sw.startedAt.should.be.above(1412706791719);
    return (sw.stoppedAt == null).should.be["true"];
  });
});

describe('Start', function() {
  return it('everything OK', function() {
    var sw;
    sw = new Stopwatch(false);
    (sw.startedAt == null).should.be["true"];
    sw.start();
    sw.startedAt.should.be.above(1412706791719);
    (sw.stoppedAt == null).should.be["true"];
    sw = Stopwatch.create(false);
    (sw.startedAt == null).should.be["true"];
    sw.start();
    sw.startedAt.should.be.above(1412706791719);
    return (sw.stoppedAt == null).should.be["true"];
  });
});

describe('Stop', function() {
  return it('everything OK', function() {
    var sw;
    sw = new Stopwatch;
    sw.startedAt.should.be.above(1412706791719);
    (sw.stoppedAt == null).should.be["true"];
    sw.stop();
    sw.stoppedAt.should.be.above(1412706791719);
    sw = Stopwatch.create();
    sw.startedAt.should.be.above(1412706791719);
    (sw.stoppedAt == null).should.be["true"];
    sw.stop();
    return sw.stoppedAt.should.be.above(1412706791719);
  });
});

describe('Result', function() {
  it('not started yet', function() {
    var sw;
    sw = new Stopwatch(false);
    (sw.startedAt == null).should.be["true"];
    (sw.stoppedAt == null).should.be["true"];
    (function() {
      return sw.result();
    }).should["throw"]('You have to start stopwatch first!');
    sw = Stopwatch.create(false);
    (sw.startedAt == null).should.be["true"];
    (sw.stoppedAt == null).should.be["true"];
    return (function() {
      return sw.result();
    }).should["throw"]('You have to start stopwatch first!');
  });
  return it('everything OK', function() {
    var sw;
    sw = new Stopwatch;
    sw.startedAt.should.be.above(1412706791719);
    (sw.stoppedAt == null).should.be["true"];
    setTimeout(function() {
      var res;
      res = sw.result();
      res.should.be.above(10);
      return res.should.equal(sw.stoppedAt - sw.startedAt);
    }, 10);
    sw = Stopwatch.create();
    sw.startedAt.should.be.above(1412706791719);
    (sw.stoppedAt == null).should.be["true"];
    return setTimeout(function() {
      var res;
      res = sw.result();
      res.should.be.above(10);
      return res.should.equal(sw.stoppedAt - sw.startedAt);
    }, 10);
  });
});
