// Generated by CoffeeScript 1.7.1
var should, utils;

should = require('chai').should();

utils = require('../lib/utils.js');

describe('isDomain', function() {
  it('wrong domains', function() {
    utils.isDomain('http://www.tomaskavka.cz').should.be["false"];
    utils.isDomain('www.tomaskavka.cz').should.be["false"];
    return utils.isDomain('192.168.0.19').should.be["false"];
  });
  return it('OK', function() {
    return utils.isDomain('tomaskavka.cz').should.be["true"];
  });
});

describe('isIPAddress', function() {
  it('wrong IP addresses', function() {
    utils.isIPAddress('http://www.tomaskavka.cz').should.be["false"];
    utils.isIPAddress('256.2.2').should.be["false"];
    return utils.isIPAddress('256.168.0.19').should.be["false"];
  });
  return it('OK', function() {
    return utils.isIPAddress('225.19.19.19').should.be["true"];
  });
});

describe('isURL', function() {
  it('wrong URL addresses', function() {
    utils.isURL('tomaskavka.cz').should.be["false"];
    utils.isURL('ftp://www.tomaskavka.cz').should.be["false"];
    return utils.isURL('225.168.0.19').should.be["false"];
  });
  return it('OK', function() {
    utils.isURL('http://www.tomaskavka.cz').should.be["true"];
    utils.isURL('https://www.tomaskavka.cz').should.be["true"];
    return utils.isURL('http://www.tomaskavka.cz/test').should.be["true"];
  });
});
