// Generated by CoffeeScript 1.7.1
var utils, _;

_ = require('lodash');

utils = (function() {
  function utils() {}

  utils.DOMAIN_PATTERN = /([^.]*\.[^.]*)$/;

  utils.IP_PATTERN = /\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/;

  utils.URL_PATTERN = /^(?:(?:https?|ftp):\/\/)(?:\S+(?::\S*)?@)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))(?::\d{2,5})?(?:\/\S*)?$/i;

  utils.isDomain = function(str) {
    if (!_.isString(str)) {
      return false;
    }
    return str === str.match(utils.DOMAIN_PATTERN)[0];
  };

  utils.isIPAddress = function(str) {
    if (!_.isString(str)) {
      return false;
    }
    return str.match(utils.IP_PATTERN) != null;
  };

  utils.isURL = function(str) {
    var match;
    if (!_.isString(str)) {
      return false;
    }
    match = str.match(utils.URL_PATTERN);
    if (match != null) {
      return str === match[0];
    } else {
      return false;
    }
  };

  utils.between = function(number, min, max) {
    if (!_.isNumber(number) || !_.isNumber(min) || !_.isNumber(max)) {
      return false;
    }
    return (min <= number && number <= max);
  };

  utils.isInt = function(num) {
    return _.isNumber(num) && num % 1 === 0;
  };

  return utils;

})();

utils.Stopwatch = require('./stopwatch');

module.exports = utils;
