// Generated by CoffeeScript 1.7.1
var utils, _;

_ = require('lodash');

utils = (function() {
  function utils() {}

  utils.DOMAIN_PATTERN = /([^.]*\.[^.]*)$/;

  utils.IP_PATTERN = /\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/;

  utils.URL_PATTERN = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/gi;

  utils.isDomain = function(str) {
    if (!_.isString(str)) {
      return false;
    }
    return str === str.match(utils.DOMAIN_PATTERN)[0];
  };

  utils.isIPAddress = function(str) {
    if (!_.isString(str)) {
      return false;
    }
    return str.match(utils.IP_PATTERN) != null;
  };

  utils.isURL = function(str) {
    var match;
    if (!_.isString(str)) {
      return false;
    }
    match = str.match(utils.URL_PATTERN);
    if (match != null) {
      return str === match[0];
    } else {
      return false;
    }
  };

  utils.between = function(number, min, max) {
    if (!_.isNumber(number) || !_.isNumber(min) || !_.isNumber(max)) {
      return false;
    }
    return (min <= number && number <= max);
  };

  return utils;

})();

utils.Stopwatch = require('./stopwatch');

module.exports = utils;
